{
 "title": "cash",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Daily cash",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"datatime\",1d),\n  ROUND((sum((data->'value')::numeric) * (select kwhprice from sites where siteid=1723771) / 1000), 1) as \"Deviation Daily Cash\"\nFROM iowatt\nWHERE\n  $__timeFilter(\"datatime\")\n  and label = 'energy'\n  and siteid = 1723771\nGROUP BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"datatime\",1d),\n  ROUND((sum((data->'value')::numeric) * (select kwhprice from sites where siteid=2168697) / 1000), 1) as \"Boris Daily Cash\"\nFROM iowatt\nWHERE\n  $__timeFilter(\"datatime\")\n  and label = 'energy'\n  and siteid = 2168697\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Monthly cash",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datatime,1M),\n  ROUND((sum((data->'value')::numeric) * (select kwhprice from sites where siteid=1723771) / 1000), 1) as \"Deviation\"\nFROM iowatt\nWHERE\n  $__timeFilter(datatime)\n  and label = 'energy'\n  and siteid = 1723771\nGROUP BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datatime,1M),\n  ROUND((sum((data->'value')::numeric) * (select kwhprice from sites where siteid=2168697) / 1000), 1) as \"Boris\"\nFROM iowatt\nWHERE\n  $__timeFilter(datatime)\n  and label = 'energy'\n  and siteid = 2168697\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Deviation cash from start",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nROUND((sum((data->'value')::numeric) * (select kwhprice from sites where siteid=1723771) / 1000), 1) as \"Deviation Daily Cash\"\nFROM iowatt\nWHERE\n  label = 'energy'\n  and siteid = 1723771"
    }
   ]
  },
  {
   "title": "Boris cash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nROUND((sum((data->'value')::numeric) * (select kwhprice from sites where siteid=2168697) / 1000), 1) as \"Deviation Daily Cash\"\nFROM iowatt\nWHERE\n  label = 'energy'\n  and siteid = 2168697"
    }
   ]
  }
 ]
}