{
 "title": "meteo",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  temperature\nFROM temperature\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pression",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  pression\nFROM pression\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sun Radiation (30min average)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  radiation\nFROM radiation\nORDER BY 1"
    }
   ]
  }
 ]
}