{
 "title": "Production",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Deviation Production (15 min average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datatime AT TIME ZONE 'Europe/Paris' AS \"time\",\n  (data->'value')::numeric as energy\nFROM\n  iowatt\nWHERE\n  $__timeFilter(datatime)\n  and label = 'energy'\n  and siteid = 1723771"
    }
   ]
  },
  {
   "title": "Boris Production (15 min average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datatime AT TIME ZONE 'Europe/Paris' AS \"time\",\n  (data->'value')::numeric as energy\nFROM\n  iowatt\nWHERE\n  $__timeFilter(datatime)\n  and label = 'energy'\n  and siteid = 2168697"
    }
   ]
  },
  {
   "title": "Sun Radiation (30min average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AT TIME ZONE 'Europe/Paris' AS \"time\",\n  radiation\nFROM radiation\nORDER BY 1"
    }
   ]
  }
 ]
}