export SOLAREDGE_SITE_ID=1723771
export SOLAREDGE_API_KEY=MVS3QYRH833HCVWAL63EH7HV2HBXCUWZ
export PG_HOST=iowatt.cailfs2k65yh.eu-west-3.rds.amazonaws.com
export PG_DB=postgres
export PG_USER=postgres
export PG_PASS=QHL5UmFLGr
export SOLAREDGE_INVERTER_SERIAL=7E0951C9-A1
